authors:
  zikai:
    name: Zikai Wang
    description: Research Engineer
    avatar: https://github.com/khaiwang.png
  jaden:
    name: Jaden Fiotto-Kaufman
    description: Creator of NNsight
    avatar: https://github.com/JadenFiotto-Kaufman.png
  ndif-team:
    name: NDIF Team
    description: National Deep Inference Fabric
    avatar: ../assets/NDIF_Favicon_color.png
  adam:
    name: Adam Belfki
    description: Research Engineer
    avatar: https://github.com/AdamBelfki3.png
